# 智普AI配置示例
ai:
  model:
    # 智普AI模型配置
    zhipu-ai:
      # 基础配置
      api-key: "${ZHIPU_AI_API_KEY:your-api-key-here}"
      base-model: "glm-4"
      api-endpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
      
      # 模型参数
      max-tokens: 2048
      temperature: 0.7
      top-p: 0.9
      
      # 网络配置
      timeout: 30000  # 30秒
      max-retries: 3
      
      # 模型信息
      name: "智普AI GLM-4"
      description: "智普AI最新的大语言模型"
      
      # 功能特性
      features:
        - text-generation
        - chat
        - streaming
        - function-calling
        
      # 支持的模型列表
      supported-models:
        - id: "glm-4"
          name: "GLM-4"
          description: "最新的大语言模型，支持多轮对话和复杂推理"
          max-tokens: 8192
          context-length: 128000
          
        - id: "glm-3-turbo"
          name: "GLM-3-Turbo"
          description: "快速响应模型，适合实时对话场景"
          max-tokens: 4096
          context-length: 64000
          
        - id: "glm-4v"
          name: "GLM-4V"
          description: "多模态模型，支持图像和文本理解"
          max-tokens: 4096
          context-length: 64000
          
        - id: "cogview-3"
          name: "CogView-3"
          description: "图像生成模型，支持文本到图像生成"
          max-tokens: 1024
          context-length: 32000

# 日志配置
logging:
  level:
    com.aiflow.aimodel.adapter.impl.ZhipuAiAdapter: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

# 环境变量配置说明
# ZHIPU_AI_API_KEY: 智普AI的API密钥
# 可以通过环境变量设置，避免在代码中硬编码敏感信息
